use serde::Deserialize;

/// Activity info
///
/// contains:
/// - activity info
#[derive(Debug, Deserialize)]
pub struct Activity {
    pub event_type: String,
    pub event_id: String,
    // pub event_source: String,
    pub user_id: String,
    pub domain: String,
    // pub freight_hostname: String,
    // pub ip: String,
    // pub day: String,
    // pub detected_locale: String,
    // - pub user_is_authenticated: bool,
    // - pub accessibility_support_enabled: bool,
    // - pub accessibility_features: String,
    // pub browser_user_agent: String,
    // pub browser: String,
    // pub device: String,
    // pub os: String,
    // pub os_version: String,
    // pub os_sdk_version: String,
    // - pub system_locale: String,
    // pub client_build_number: String,
    // pub client_version: String,
    // - pub client_performance_cpu: u32,
    // - pub client_performance_memory: String,
    // pub city: String,
    // pub country_code: String,
    // pub region_code: String,
    // pub time_zone: String,
    // pub isp: String,
    // - pub gateway_connection: String,
    // - pub gateway_hello: String,
    // - pub voice_connection: String,
    // - pub stream_requested: String,
    // - pub stream_connection: String,
    // - pub stream_first_frame: String,
    // - pub video_first_frame: String,
    // - pub media_engine_connection: String,
    // - pub connection_video_first_frame: String,
    // - pub connection_stream_first_frame: String,
    // - pub event_time_name: String,
    // - pub cpu_core_count: String,
    // - pub _source_job_id: String,
    // - pub _ingest_ts: String,
    pub accepted_languages: Vec<String>,
    pub accepted_languages_weighted: Vec<String>,
    // - pub primary_accepted_language: String,
    // - pub _hour_pt: String,
    // - pub _hour_utc: String,
    // - pub _day_pt: String,
    // - pub _day_utc: String,
    pub client_send_timestamp: String,
    pub client_track_timestamp: String,
    pub timestamp: String,
}
